services:
  - type: web
    name: local-business-dashboard-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://jovial-kheer-b98df6.netlify.app 